"""Criterion C1 of the P1 preregistration: targets are exactly equal.

``docs/preregistration/P1-selfsupervised-moving-average.md`` registers, before
any of the port existed, that :func:`moving_average_targets` must reproduce the
archived reference implementation **exactly** on five cases. The reference is
not part of this repository; its targets are pinned as sha256 digests in
``fixtures/p1_reference_targets.json``, regenerated by the script beside them.

Exact equality is demanded rather than a tolerance: a difference here means the
ported algorithm differs, and a tolerance would hide that. The one exception the
preregistration allows is a demonstrated ``numpy.argsort`` tie-break difference,
which is diagnosed rather than charged to the port — see
:func:`test_c1_case_a_is_tie_break_sensitive`, which records that sensitivity so
a future numpy change is read correctly instead of as a port defect.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import numpy as np
import pytest

from dnndenoiser.training.selfsupervised import moving_average_targets

PINNED = json.loads(
    (Path(__file__).parent / "fixtures" / "p1_reference_targets.json").read_text()
)
CASES = PINNED["cases"]


def digest(a: np.ndarray) -> str:
    return hashlib.sha256(np.ascontiguousarray(a).tobytes()).hexdigest()


@pytest.fixture(scope="module")
def frames() -> np.ndarray:
    """The preregistration's fixture, built from its constants alone.

    Deliberately not imported from anywhere: the point of restating the constants
    in the preregistration is that the fixture can be rebuilt from the document.
    """
    rng = np.random.default_rng(1)
    energy = np.linspace(0, 1, 256)
    clean = 300 * np.exp(-((energy - 0.5) ** 2) / (2 * 0.04**2)) + 20
    f = rng.poisson(np.tile(clean, (200, 1))).astype(np.float32)
    g_min, g_max = f.min(), f.max()
    assert (g_min, g_max) == (5.0, 387.0), "fixture drifted from the registered constants"
    return (f - g_min) / (g_max - g_min)


@pytest.mark.parametrize("W", [1, 2, 5, 10])
def test_c1_case_a_arange_order(frames, W):
    """C1(a) — the paper's W sweep on contiguous acquisition order."""
    got = moving_average_targets(frames, np.arange(len(frames)), W)
    assert got.dtype == np.float64
    assert digest(got) == CASES[f"a_arange_W{W}"]["sha256"]


def test_c1_case_b_permuted_order(frames):
    """C1(b) — acquisition order must actually be used.

    On ``arange`` the temporal distance equals the row distance, so an
    implementation that ignores ``frame_indices`` and windows by row position
    passes every other case. This is the one that catches it.
    """
    permuted = np.random.default_rng(7).permutation(len(frames))
    got = moving_average_targets(frames, permuted, 5)
    assert digest(got) == CASES["b_permuted_W5"]["sha256"]


def test_c1_case_b_actually_discriminates_positional_windowing(frames):
    """The guard on C1(b) itself: a positional port must fail it.

    Without this, a later refactor could make C1(b) vacuous without anyone
    noticing.
    """
    permuted = np.random.default_rng(7).permutation(len(frames))
    by_position = moving_average_targets(frames, np.arange(len(frames)), 5)
    by_order = moving_average_targets(frames, permuted, 5)
    assert not np.array_equal(by_position, by_order)
    assert np.abs(by_position - by_order).max() > 0.1


def test_c1_case_c_window_clamps_to_available_frames(frames):
    """C1(c) — ``W`` larger than the stack clamps to ``n - 1``."""
    got = moving_average_targets(frames[:3], np.arange(3), 10)
    assert got.shape == (3, 256)
    assert digest(got) == CASES["c_clamp_n3_W10"]["sha256"]
    assert np.array_equal(got, moving_average_targets(frames[:3], np.arange(3), 2))


@pytest.mark.parametrize(
    "n_frames, W",
    [(1, 5), (2, 0), (200, 0), (200, -1)],
    ids=["one-frame", "two-frames-W0", "W0", "negative-W"],
)
def test_c1_case_d_no_neighbourhood_raises(frames, n_frames, W):
    """C1(d) — ``ValueError`` where no leave-one-out neighbourhood exists.

    Note two frames with ``W >= 1`` is *valid* (the window clamps to 1); it is
    one frame, or a non-positive window, that has no neighbourhood.
    """
    with pytest.raises(ValueError):
        moving_average_targets(frames[:n_frames], np.arange(n_frames), W)


def test_c1_two_frames_is_valid(frames):
    """The boundary the raise must not swallow."""
    got = moving_average_targets(frames[:2], np.arange(2), 5)
    assert np.array_equal(got[0], frames[1].astype(np.float64))
    assert np.array_equal(got[1], frames[0].astype(np.float64))


def test_c1_case_e_duplicate_indices_reproduce_the_reference(frames):
    """C1(e) — duplicated acquisition indices, pinned to the reference.

    Exclusion is by position, not by index value, so a duplicate becomes a
    distance-0 "other" frame. The behaviour is pinned because it is reachable
    from a user-written file; the reader rejects duplicates so it is not reached
    in practice.
    """
    duplicated = np.arange(len(frames))
    duplicated[1] = duplicated[0]
    got = moving_average_targets(frames, duplicated, 5)
    assert digest(got) == CASES["e_duplicate_index_W5"]["sha256"]

    # The hazard, stated sharply: at W=1 frame 0's whole target *is* frame 1,
    # because the duplicate sits at distance 0 and wins the single slot. At
    # larger W it is one of the averaged neighbours rather than the whole
    # target, which is why the leak is easy to miss.
    assert np.array_equal(
        moving_average_targets(frames, duplicated, 1)[0],
        frames[1].astype(np.float64),
    ), "a duplicate index leaks the other frame directly into the target"


def test_c1_case_a_is_tie_break_sensitive(frames):
    """Diagnostic, not a criterion: record that odd W depends on the tie-break.

    Distances from evenly spaced indices come in symmetric pairs, so for odd
    ``W`` the outermost neighbour is a genuine tie decided by ``numpy.argsort``'s
    default (unstable) ordering. If a future numpy changes it, C1 will fail at
    W=1 and W=5 and pass at W=2 and W=10 — this test says so out loud, so the
    failure is diagnosed rather than charged to the port.
    """
    n = len(frames)
    t = np.arange(n, dtype=np.float64)
    d = np.abs(t[:, None] - t[None, :])
    np.fill_diagonal(d, np.inf)
    sensitive = {}
    for W in (1, 2, 5, 10):
        default = np.argsort(d, axis=1)[:, :W]
        stable = np.argsort(d, axis=1, kind="stable")[:, :W]
        sensitive[W] = sum(
            1 for i in range(n) if set(default[i]) != set(stable[i])
        )
    assert sensitive[2] == 0 and sensitive[10] == 0, "even W should never tie at the edge"
    assert sensitive[1] > 0 and sensitive[5] > 0, "odd W is expected to be tie-sensitive"
